-- Supabase schema for the SWE internship scraper.
-- Safe to run more than once in the Supabase SQL editor.

create table if not exists public.swe_internship_postings (
  id bigint generated by default as identity not null,
  hash character varying not null,
  company character varying not null,
  role character varying not null,
  location character varying null,
  link_to_posting character varying null,
  created_at timestamp with time zone not null default now(),
  scraped_at timestamp with time zone null,
  constraint swe_internship_postings_pkey primary key (id),
  constraint swe_internship_postings_hash_key unique (hash)
) tablespace pg_default;

alter table public.swe_internship_postings
  add column if not exists location character varying null;

alter table public.swe_internship_postings
  add column if not exists scraped_at timestamp with time zone null;

create index if not exists idx_swe_internship_postings_hash
  on public.swe_internship_postings(hash);

create index if not exists idx_swe_internship_postings_scraped_at
  on public.swe_internship_postings(scraped_at);

alter table public.swe_internship_postings enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.swe_internship_postings to service_role;
grant usage, select on all sequences in schema public to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'swe_internship_postings'
      and policyname = 'github_actions_scraper_select'
  ) then
    create policy github_actions_scraper_select
      on public.swe_internship_postings
      for select
      to service_role
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'swe_internship_postings'
      and policyname = 'github_actions_scraper_insert'
  ) then
    create policy github_actions_scraper_insert
      on public.swe_internship_postings
      for insert
      to service_role
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'swe_internship_postings'
      and policyname = 'github_actions_scraper_delete'
  ) then
    create policy github_actions_scraper_delete
      on public.swe_internship_postings
      for delete
      to service_role
      using (true);
  end if;
end
$$;
